![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [2]:
import numpy as np

lista = [0,1,2,3,4,5,6,7,8,9]

my_array = np.array(lista)
my_array

my_array[::-1][::2]

array([9, 7, 5, 3, 1])

In [3]:
np.arange(0,10,1)[::-2]

array([9, 7, 5, 3, 1])

## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [40]:
my_array[-2:][::-1]

#array [-2:][::-1]

my_array[7:9:][::-1]

array([8, 7])

## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [44]:
my_array[0:3:][::-1]

array([2, 1, 0])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [73]:
array1 = np.arange(1,21).reshape(4,5)
array1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [74]:
array1[::-1,::-1]


array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [75]:
array1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [81]:
array1[:2, :2]

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [87]:
array1[::2, ::2]

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [111]:
array1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [110]:
array1[:3:1, ::-1]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [5]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
lista_loro = []

for animal in x:
    if animal == "Loro":
        lista_loro.append(animal)


array_loro =np.array(lista_loro)
print (array_loro)

['Loro' 'Loro']


In [10]:
#resolverlo con mask
x[x=="Loro"]

array(['Loro', 'Loro'], dtype='<U5')

In [11]:
#resolverlo con where
np.where(x=="Loro", "Loro", False)

array(['Loro', 'False', 'False', 'Loro', 'False'], dtype='<U5')

## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [131]:
secuencia = np.arange(20)
secuencia

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [133]:
secuencia.reshape(2,5,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [124]:
array1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [126]:
array1[::-1, ::-1]

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [26]:
#full tiene dos argumentos =size, que en este caso es 10 y value que en este caso es 0
a =np.full((10), 0)
a.itemsize
a



array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
a[3]=1
a

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0])

## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [129]:
vector = np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [130]:
vector[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [27]:
matriz13 = [1,2,0,0,4,0]
my_matrix13 =np.array(matriz13)
my_matrix13

array([1, 2, 0, 0, 4, 0])

In [36]:
np.argwhere(my_matrix13==0)

array([[2],
       [3],
       [5]])

In [34]:
np.argwhere([1,2,0,0,4,0])

array([[0],
       [1],
       [4]])

In [39]:
#para que te los ponga todos en la misma linea
np.argwhere([1,2,0,0,4,0]).reshape(-1)

array([0, 1, 4])

In [ ]:
#tambien se podria haber resuelto con un bucle for y un if

## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [148]:
matriz14 = np.random.randint(10, size = (10,10))
matriz14

array([[8, 0, 1, 5, 4, 9, 3, 6, 6, 0],
       [3, 8, 4, 7, 1, 4, 8, 5, 4, 3],
       [1, 3, 5, 9, 0, 0, 6, 7, 5, 9],
       [6, 4, 8, 6, 5, 5, 1, 9, 0, 5],
       [3, 1, 8, 8, 6, 5, 1, 4, 5, 9],
       [2, 5, 3, 2, 2, 1, 2, 9, 3, 9],
       [3, 8, 5, 7, 6, 1, 2, 7, 9, 5],
       [7, 7, 7, 3, 6, 1, 4, 2, 7, 4],
       [5, 0, 2, 6, 9, 3, 9, 4, 5, 7],
       [3, 7, 7, 1, 6, 7, 5, 3, 0, 4]])

In [153]:
print (np.min(matriz14))

print (np.max(matriz14))

0
9


In [146]:
matriz_14 = np.random.rand (10,10)
matriz14

array([[9, 5, 8, 4, 6, 1, 4, 1, 7, 4],
       [1, 4, 1, 4, 1, 9, 9, 7, 4, 0],
       [6, 0, 0, 4, 4, 0, 8, 8, 9, 6],
       [5, 7, 3, 0, 7, 6, 5, 5, 8, 6],
       [8, 2, 2, 5, 9, 5, 5, 0, 1, 2],
       [1, 5, 5, 5, 5, 7, 9, 3, 3, 4],
       [3, 6, 7, 9, 9, 9, 4, 7, 7, 4],
       [7, 6, 8, 1, 2, 8, 4, 9, 9, 7],
       [7, 0, 5, 4, 1, 0, 2, 4, 4, 4],
       [5, 8, 4, 1, 0, 7, 4, 3, 6, 4]])

In [42]:
np.random.rand(10,10)

array([[0.88184895, 0.86368345, 0.16810048, 0.19090411, 0.17888364,
        0.9516609 , 0.59249209, 0.82208287, 0.35113701, 0.62795595],
       [0.95872954, 0.21630191, 0.76669641, 0.14605315, 0.76112971,
        0.10381789, 0.33460904, 0.75504592, 0.94577222, 0.80045435],
       [0.94909562, 0.62236402, 0.91418389, 0.44693238, 0.1023612 ,
        0.28748523, 0.69478735, 0.09363598, 0.58689934, 0.47085101],
       [0.55950901, 0.34143521, 0.45563156, 0.13256401, 0.04606843,
        0.64279503, 0.05460827, 0.03597055, 0.92623662, 0.64401478],
       [0.91557822, 0.67277309, 0.42781457, 0.58870775, 0.03939224,
        0.52199134, 0.48358433, 0.32181526, 0.45261924, 0.96880055],
       [0.73611958, 0.85682453, 0.82928184, 0.90422661, 0.03425065,
        0.08942076, 0.50791969, 0.07463241, 0.1285429 , 0.79148874],
       [0.34261026, 0.9716896 , 0.83825732, 0.91484981, 0.82824557,
        0.57939689, 0.55144292, 0.8369598 , 0.1884221 , 0.87777865],
       [0.33165183, 0.72522564, 0.7570277

In [43]:
np.random.rand(10,10).min()

np.float64(0.005644482577352283)

In [44]:
np.random.rand(10,10).max()

np.float64(0.99306888979373)

## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [157]:
matrix15 = np.random.randint(10, size=(1,30))
matrix15

array([[2, 3, 2, 4, 0, 5, 4, 8, 7, 1, 1, 1, 3, 5, 0, 5, 3, 5, 5, 3, 0, 1,
        4, 2, 5, 6, 2, 9, 3, 5]])

In [161]:
np.median(matrix15)

np.float64(3.0)

In [47]:
np.random.randn(30).mean()

np.float64(-0.10856882998645666)

## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [190]:
a = np.ones((5,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [196]:

a[1:4: , 1:4:]=0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [197]:
a = np.ones((8,8))
a

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [201]:
a [::2 ,::2 ] = 0 
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [202]:
a [1::2 ,1::2 ] = 0 
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [50]:
a1 = np.ones((8,8))
a1

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [52]:
np.tile([[0,1], [1,0]], (4,4))


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [53]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [60]:
#Randint tienes que insertarle = low, high, size
m = np.random.randint(1,10, (5,5))
media = m.mean()
std = m.std()


In [65]:
plt.hist((((m-media)/std.flatten());

SyntaxError: invalid syntax (3857169928.py, line 1)

In [66]:
matrix4 = np.random.randint(1,10, (5,5))
media = np.mean(matrix4)
desv = np.std(matrix4)
normalizada = (matrix4 - media)/desv

## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [70]:
seq = np.arange (0,11)
seq

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
seq[(3<=seq) & (seq<=8)] = -1

In [75]:
seq

array([ 0,  1,  2, -1, -1, -1, -1, -1, -1,  9, 10])

## Ejercicio 21
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.